### PR TITLE
Use rosconsole to set logger levels. Fixes #7

### LINKED ISSUE #7: Missing log4cxx headers when building against latest ros_comm.
When building against the latest development version of ros_comm, which attempts to remove the dependency on log4cxx, hokuyo_node fails to build with the following error:

```
[ 40%] Building CXX object CMakeFiles/getFirmwareVersion.dir/src/getFirmwareVersion.cpp.o
/usr/lib/ccache/c++   -DROS_PACKAGE_NAME=\"hokuyo_node\" -I/tmp/buildd/ros-hydro-hokuyo-node-1.7.7-0raring-20140106-2312/obj-arm-linux-gnueabihf/devel/include -I/tmp/buildd/ros-hydro-hokuyo-node-1.7.7-0raring-20140106-2312/include -I/opt/ros/hydro/include    -o CMakeFiles/getFirmwareVersion.dir/src/getFirmwareVersion.cpp.o -c /tmp/buildd/ros-hydro-hokuyo-node-1.7.7-0raring-20140106-2312/src/getFirmwareVersion.cpp
/tmp/buildd/ros-hydro-hokuyo-node-1.7.7-0raring-20140106-2312/src/getFirmwareVersion.cpp: In function 'int main(int, char**)':
/tmp/buildd/ros-hydro-hokuyo-node-1.7.7-0raring-20140106-2312/src/getFirmwareVersion.cpp:56:5: error: 'log4cxx' has not been declared
/tmp/buildd/ros-hydro-hokuyo-node-1.7.7-0raring-20140106-2312/src/getFirmwareVersion.cpp:56:24: error: expected ';' before 'my_logger'
/tmp/buildd/ros-hydro-hokuyo-node-1.7.7-0raring-20140106-2312/src/getFirmwareVersion.cpp:57:5: error: 'my_logger' was not declared in this scope
/tmp/buildd/ros-hydro-hokuyo-node-1.7.7-0raring-20140106-2312/src/getFirmwareVersion.cpp:57:25: error: 'g_level_lookup' is not a member of 'ros::console'
make[4]: *** [CMakeFiles/getFirmwareVersion.dir/src/getFirmwareVersion.cpp.o] Error 1
```

I believe the fix for this should be as simple as adding an explicit dependency on log4cxx, but it might be more involved if hokuyo_node is relying on the underlying implementation of ros logging being log4cxx.

### PR DESCRIPTION
**Pull request by trainman419**

### CODE REVIEW

**Comment by trainman419** [comment]
Don't merge this yet. See: http://answers.ros.org/question/116436/missing-log4cxx-on-latest-ros_comm/

**Comment by chadrockey** [comment]
@trainman419 We could fix this by adding our dependency on Log4Cxx and then switch to this in Indigo?

**Comment by trainman419** [comment]
There are two underlying issues here:
1. Missing the transitive log4cxx headers
   1. We can fix this by adding a dependency on log4cxx and including the headers manually
2. rosconsole no longer exposes g_level_lookup
   1. We _could_ implement our own copy of this, but it would be very brittle. I consider this a bug in rosconsole.
   2. As Dirk suggested, we could also use the log4cxx level macros directly

**Comment by dirk-thomas** [comment]
The removed symbol has been readded to ros_comm again (in ros/ros_comm#336) which has just been rereleased (1.9.53). This keeps the part of 1. in https://github.com/ros-drivers/hokuyo_node/pull/8#issuecomment-32056251 to be done.

**Comment by trainman419** [comment]
Updated and ready for review + merge.

**Comment by chadrockey** [comment]
@trainman419 Thanks for this.  Released now.

**Pull request merged**
